spring:
  application:
   name: voter_pet_project
  datasource:
   url: jdbc:postgresql://localhost:5432/Pet_Database
   username: postgres
   password: Dataparole

  jpa:
   hibernate:
    ddl-auto: validate
   show-sql: true
   properties:
    hibernate:
     format_sql: true
     dialect:
     org:
      hibernate:
       dialect:PostgreSQLDialect